- src/App.jsx
- src/assets/styles/index.js
- src/assets/styles/variables.js
add variables as ThemeProvider
> ADD: ThemeProvider

- src/assets/styles/index.js
> FIX: route to variables

- src/main.jsx
- src/redux/authSlice/operations.js
- src/redux/petsSlice/operations.js
- src/redux/petsSlice/petsSlice.js
- src/redux/store.js
> ADD: getPets

- src/App.jsx
- src/components/Notices/NoticesFilters/NoticesFilters.jsx
- src/components/Notices/NoticesFilters/NoticesFilters.style.js
- src/components/Notices/NoticesSearch/NoticesSearch.jsx
- src/components/Notices/NoticesSearch/NoticesSearch.style.js
- src/components/SharedLayout/Header/Header.jsx
- src/routes/PrivateRoute.jsx
- src/routes/PublicRoute.jsx
+ приватні роути
+ onClick з видаленням на хрестик
> add private routes

- src/components/Notices/NoticesCategoriesList/NoticesCategoriesList.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/redux/noticesSlice/noticesSlice.js
- src/redux/noticesSlice/operations.js
- src/redux/selectors.js
- src/redux/store.js
- notieces operations
- get notieces from store
> ADD: fetch notices

- src/components/Forms/LoginForm/LoginForm.jsx
- src/redux/authSlice/operations.js
> ADD: login distatch

- src/App.jsx
- src/components/Forms/AddPetForm/AddPetForm/AddPetForm.jsx
- src/components/Forms/AddPetForm/AddPetFormsContainer/AddPetFormsContainer.jsx
- src/components/Forms/AddPetForm/AddPetFormsContainer/AddPetFormsContainer.styled.js
- src/components/Forms/AddPetForm/AddPetMultiStepForm.jsx
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.jsx
- src/components/Forms/AddPetForm/PersonalDetailsForm/PersonalDetailsForm.jsx
- src/components/Forms/AddPetForm/PersonalDetailsForm/PersonaleDetailsForm.styled.js
> ADD: styles

- src/components/Modals/ModalNotice/ModalNotice.jsx
- src/components/Modals/ModalNotice/ModalNotice.styled.jsx
- src/components/Notices/NoticesCategoriesList/NoticesCategoriesList.jsx
- src/components/Notices/NoticesCategoriesList/NoticesPetCard.styled.js
- src/components/Notices/NoticesSearch/NoticesSearch.jsx
- src/redux/selectors.js
- src/utils/formatDate.js
- src/utils/formatYears.js
- src/utils/index.js
add: visibleCards | NoticesCategoriesList
> add: visibleCards | NoticesCategoriesList

- src/components/Notices/NoticesCategoriesList/NoticesCategoriesList.jsx
- src/components/Notices/NoticesSearch/NoticesSearch.jsx
- src/pages/NoticesPage/NoticesPage.jsx
> fix: console

- src/components/Forms/AddPetForm/AddPetMultiStepForm.jsx
- src/components/Forms/AddPetForm/FormBtnNav/FormBtnNav.jsx
- src/components/Forms/AddPetForm/OptionForm/OptionForm.jsx
- src/redux/petsSlice/petsSlice.js
- src/redux/petsSlice/selectors.js
- src/redux/selectors.js
> FIX: add-pet-form

- src/App.jsx
- src/components/SharedLayout/UserNav/UserNav.jsx
- src/redux/authSlice/operations.js
> ADD: refresh

- src/components/Forms/AddPetForm/AddPetMultiStepForm.jsx
- src/components/Forms/AddPetForm/FormBtnNav/FormBtnNav.jsx
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.jsx
- src/components/Forms/AddPetForm/OptionForm/OptionForm.jsx
- src/components/Forms/AddPetForm/PersonalDetailsForm/DetailsForm.jsx
- src/components/Forms/AddPetForm/PersonalDetailsForm/DetailsForm.styled.js
- src/redux/petsSlice/petsSlice.js
> ADD: personal details form

- src/components/Forms/UserForm/UserAvatar.jsx
- src/components/Forms/UserForm/UserAvatar.styled.jsx
- src/components/Forms/UserForm/UserForm.styled.jsx
- src/pages/UserPage/UserPage.jsx
- src/pages/UserPage/UserPage.styled.jsx
- src/pages/UserPage/UserPetsSection.jsx
- src/pages/UserPage/UserPetsSection.styled.jsx
> styled full

- src/components/News/NewsSearch/NewsSearch.jsx
- src/components/News/NewsSearch/NewsSearch.styled.js
- src/pages/NewsPage/NewsPage.jsx
> add search

- src/components/Forms/AddPetForm/DetailsForm/DetailsForm.jsx
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.jsx
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.styled.js
- src/components/Forms/AddPetForm/OptionForm/OptionForm.jsx
- src/redux/petsSlice/operations.js
- src/redux/petsSlice/petsSlice.js
- src/redux/petsSlice/selectors.js
1. more info form 
2. final submit
3. operation fot addPet query
4. fix DetailsForm
5. fix selectors
> ADD: more info form

- src/components/Forms/UserForm/UserForm.jsx
- src/components/Modals/ModalApproveAction/ModalApproveAction.jsx
- src/components/Modals/ModalApproveAction/ModalApproveAction.styled.jsx
- src/components/Modals/ModalComponents/ModalComponents.styled.jsx
- src/components/Modals/ModalCongrats/ModalCongrats.jsx
> add: ModalApproveAction

- src/App.jsx
- src/components/Forms/AddPetForm/OptionForm/OptionForm.jsx
- src/components/Forms/AddPetForm/OptionForm/OptionForm.styled.js
- src/components/SharedLayout/UserNav/UserNav.jsx
> ADD: Formik got option form

- src/App.jsx
- src/components/Forms/AddPetForm/AddPetMultiStepForm.jsx
- src/components/Forms/AddPetForm/DetailsForm/DetailsForm.jsx
- src/components/Forms/AddPetForm/FormBtnNav/FormBtnNav.jsx
- src/components/Forms/AddPetForm/FormBtnNav/FormBtnNav.styled.js
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.jsx
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.styled.js
- src/components/Forms/AddPetForm/OptionForm/OptionForm.jsx
- src/components/Forms/AddPetForm/OptionForm/OptionForm.styled.js
- src/components/Forms/AddPetForm/SuccessStage/SuccessStage.jsx
- src/redux/authSlice/operations.js
- src/redux/noticesSlice/noticesSlice.js
- src/redux/petsSlice/operations.js
- src/redux/petsSlice/petsSlice.js
> ADD: fix upload

- src/components/Forms/UserForm/UserAvatar.jsx
- src/components/Forms/UserForm/UserAvatar.styled.jsx
- src/redux/authSlice/authSlice.js
я трошки модифікувала редюсер який оновлює фото, бо мені треба було собі вернути якось помилку якщо картинка не загрузилась
> userpage updating

- src/components/Forms/AddPetForm/AddPetMultiStepForm.jsx
- src/components/Forms/AddPetForm/AddPetMultiStepForm.styled.js
- src/components/Forms/AddPetForm/DetailsForm/DetailsForm.jsx
- src/components/Forms/AddPetForm/DetailsForm/DetailsForm.styled.js
- src/components/Forms/AddPetForm/FormBtnNav/FormBtnNav.jsx
- src/components/Forms/AddPetForm/FormBtnNav/FormBtnNav.styled.js
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.jsx
- src/components/Forms/AddPetForm/MoreInfoForm/MoreInfoForm.styled.js
- src/components/Forms/AddPetForm/OptionForm/OptionForm.jsx
- src/components/Forms/AddPetForm/OptionForm/OptionForm.styled.js
> ADD: saving data

- src/components/Modals/ModalNotice/ModalNotice.jsx
- src/components/Notices/CommonItemList/CommonItemList.jsx
- src/components/Notices/NoticesCategoriesList/NoticesCategoriesList.jsx
- src/redux/noticesSlice/noticesSlice.js
- src/redux/noticesSlice/operations.js
> fix: Favorite
